/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EkonomickySubjektCeuZaklad
 */
public class EkonomickySubjektCeuZakladTest {
    private final EkonomickySubjektCeuZaklad model = new EkonomickySubjektCeuZaklad();

    /**
     * Model tests for EkonomickySubjektCeuZaklad
     */
    @Test
    public void testEkonomickySubjektCeuZaklad() {
        // TODO: test EkonomickySubjektCeuZaklad
    }

    /**
     * Test the property 'ico'
     */
    @Test
    public void icoTest() {
        // TODO: test ico
    }

    /**
     * Test the property 'obchodniJmeno'
     */
    @Test
    public void obchodniJmenoTest() {
        // TODO: test obchodniJmeno
    }

    /**
     * Test the property 'sidlo'
     */
    @Test
    public void sidloTest() {
        // TODO: test sidlo
    }

    /**
     * Test the property 'pravniForma'
     */
    @Test
    public void pravniFormaTest() {
        // TODO: test pravniForma
    }

    /**
     * Test the property 'financniUrad'
     */
    @Test
    public void financniUradTest() {
        // TODO: test financniUrad
    }

    /**
     * Test the property 'datumVzniku'
     */
    @Test
    public void datumVznikuTest() {
        // TODO: test datumVzniku
    }

    /**
     * Test the property 'datumZaniku'
     */
    @Test
    public void datumZanikuTest() {
        // TODO: test datumZaniku
    }

    /**
     * Test the property 'datumAktualizace'
     */
    @Test
    public void datumAktualizaceTest() {
        // TODO: test datumAktualizace
    }

    /**
     * Test the property 'dic'
     */
    @Test
    public void dicTest() {
        // TODO: test dic
    }

    /**
     * Test the property 'typSubjektu'
     */
    @Test
    public void typSubjektuTest() {
        // TODO: test typSubjektu
    }

    /**
     * Test the property 'adresy'
     */
    @Test
    public void adresyTest() {
        // TODO: test adresy
    }

    /**
     * Test the property 'jmenoPrijmeni'
     */
    @Test
    public void jmenoPrijmeniTest() {
        // TODO: test jmenoPrijmeni
    }

}
