//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.24 at 01:02:52 PM CET 
//


package cz.mfcr.wwwinfo.ares.xml_doc.schemas.uvis_datatypes.v_1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.mfcr.wwwinfo.ares.xml_doc.schemas.uvis_datatypes.v_1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorList_QNAME = new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1", "Error_list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.mfcr.wwwinfo.ares.xml_doc.schemas.uvis_datatypes.v_1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XsltErrorList }
     * 
     */
    public XsltErrorList createXsltErrorList() {
        return new XsltErrorList();
    }

    /**
     * Create an instance of {@link AdresaUIR }
     * 
     */
    public AdresaUIR createAdresaUIR() {
        return new AdresaUIR();
    }

    /**
     * Create an instance of {@link XsltErrorList.Error }
     * 
     */
    public XsltErrorList.Error createXsltErrorListError() {
        return new XsltErrorList.Error();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XsltErrorList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1", name = "Error_list")
    public JAXBElement<XsltErrorList> createErrorList(XsltErrorList value) {
        return new JAXBElement<XsltErrorList>(_ErrorList_QNAME, XsltErrorList.class, null, value);
    }

}
