/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Notifikační dávka datového zdroje
 */
@ApiModel(description = "Notifikační dávka datového zdroje")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-27T00:34:55.679880400+01:00[Europe/Prague]")
public class NotifikacniDavka {
  public static final String SERIALIZED_NAME_CISLO_DAVKY = "cisloDavky";
  @SerializedName(SERIALIZED_NAME_CISLO_DAVKY)
  private Integer cisloDavky;

  public static final String SERIALIZED_NAME_DATOVY_ZDROJ = "datovyZdroj";
  @SerializedName(SERIALIZED_NAME_DATOVY_ZDROJ)
  private String datovyZdroj;

  public static final String SERIALIZED_NAME_DATUM_UVOLNENI_DAVKY = "datumUvolneniDavky";
  @SerializedName(SERIALIZED_NAME_DATUM_UVOLNENI_DAVKY)
  private LocalDate datumUvolneniDavky;

  public static final String SERIALIZED_NAME_POCET_ZMEN = "pocetZmen";
  @SerializedName(SERIALIZED_NAME_POCET_ZMEN)
  private Integer pocetZmen;

  public NotifikacniDavka() {
  }

  public NotifikacniDavka cisloDavky(Integer cisloDavky) {
    
    this.cisloDavky = cisloDavky;
    return this;
  }

   /**
   * Číslo notifikační dávky
   * @return cisloDavky
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Číslo notifikační dávky")

  public Integer getCisloDavky() {
    return cisloDavky;
  }


  public void setCisloDavky(Integer cisloDavky) {
    this.cisloDavky = cisloDavky;
  }


  public NotifikacniDavka datovyZdroj(String datovyZdroj) {
    
    this.datovyZdroj = datovyZdroj;
    return this;
  }

   /**
   * Datový zdroj notifikační dávky - kód (ciselnikKod: TypZdrojeAres, zdroj:com) 
   * @return datovyZdroj
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datový zdroj notifikační dávky - kód (ciselnikKod: TypZdrojeAres, zdroj:com) ")

  public String getDatovyZdroj() {
    return datovyZdroj;
  }


  public void setDatovyZdroj(String datovyZdroj) {
    this.datovyZdroj = datovyZdroj;
  }


  public NotifikacniDavka datumUvolneniDavky(LocalDate datumUvolneniDavky) {
    
    this.datumUvolneniDavky = datumUvolneniDavky;
    return this;
  }

   /**
   * Datum uvolnění notifikační dávky
   * @return datumUvolneniDavky
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum uvolnění notifikační dávky")

  public LocalDate getDatumUvolneniDavky() {
    return datumUvolneniDavky;
  }


  public void setDatumUvolneniDavky(LocalDate datumUvolneniDavky) {
    this.datumUvolneniDavky = datumUvolneniDavky;
  }


  public NotifikacniDavka pocetZmen(Integer pocetZmen) {
    
    this.pocetZmen = pocetZmen;
    return this;
  }

   /**
   * Počet změn v notifikační dávce
   * @return pocetZmen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Počet změn v notifikační dávce")

  public Integer getPocetZmen() {
    return pocetZmen;
  }


  public void setPocetZmen(Integer pocetZmen) {
    this.pocetZmen = pocetZmen;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifikacniDavka notifikacniDavka = (NotifikacniDavka) o;
    return Objects.equals(this.cisloDavky, notifikacniDavka.cisloDavky) &&
        Objects.equals(this.datovyZdroj, notifikacniDavka.datovyZdroj) &&
        Objects.equals(this.datumUvolneniDavky, notifikacniDavka.datumUvolneniDavky) &&
        Objects.equals(this.pocetZmen, notifikacniDavka.pocetZmen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cisloDavky, datovyZdroj, datumUvolneniDavky, pocetZmen);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotifikacniDavka {\n");
    sb.append("    cisloDavky: ").append(toIndentedString(cisloDavky)).append("\n");
    sb.append("    datovyZdroj: ").append(toIndentedString(datovyZdroj)).append("\n");
    sb.append("    datumUvolneniDavky: ").append(toIndentedString(datumUvolneniDavky)).append("\n");
    sb.append("    pocetZmen: ").append(toIndentedString(pocetZmen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cisloDavky");
    openapiFields.add("datovyZdroj");
    openapiFields.add("datumUvolneniDavky");
    openapiFields.add("pocetZmen");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to NotifikacniDavka
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (NotifikacniDavka.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotifikacniDavka is not found in the empty JSON string", NotifikacniDavka.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!NotifikacniDavka.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotifikacniDavka` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("datovyZdroj") != null && !jsonObj.get("datovyZdroj").isJsonNull()) && !jsonObj.get("datovyZdroj").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `datovyZdroj` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datovyZdroj").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotifikacniDavka.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotifikacniDavka' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotifikacniDavka> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotifikacniDavka.class));

       return (TypeAdapter<T>) new TypeAdapter<NotifikacniDavka>() {
           @Override
           public void write(JsonWriter out, NotifikacniDavka value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotifikacniDavka read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NotifikacniDavka given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NotifikacniDavka
  * @throws IOException if the JSON string is invalid with respect to NotifikacniDavka
  */
  public static NotifikacniDavka fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotifikacniDavka.class);
  }

 /**
  * Convert an instance of NotifikacniDavka to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

