/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AngazovanaOsobaRzp;
import org.openapitools.client.model.AngazovanySubjektRzp;
import org.openapitools.client.model.Zivnost;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ZaznamRzpAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-27T00:34:55.679880400+01:00[Europe/Prague]")
public class ZaznamRzpAllOf {
  public static final String SERIALIZED_NAME_SOUVISEJICI_SUBJEKTY = "souvisejiciSubjekty";
  @SerializedName(SERIALIZED_NAME_SOUVISEJICI_SUBJEKTY)
  private List<AngazovanySubjektRzp> souvisejiciSubjekty = null;

  public static final String SERIALIZED_NAME_OSOBA_PODNIKATEL = "osobaPodnikatel";
  @SerializedName(SERIALIZED_NAME_OSOBA_PODNIKATEL)
  private AngazovanaOsobaRzp osobaPodnikatel;

  public static final String SERIALIZED_NAME_ANGAZOVANE_OSOBY = "angazovaneOsoby";
  @SerializedName(SERIALIZED_NAME_ANGAZOVANE_OSOBY)
  private List<AngazovanaOsobaRzp> angazovaneOsoby = null;

  public static final String SERIALIZED_NAME_ZIVNOSTI = "zivnosti";
  @SerializedName(SERIALIZED_NAME_ZIVNOSTI)
  private List<Zivnost> zivnosti = null;

  public ZaznamRzpAllOf() {
  }

  public ZaznamRzpAllOf souvisejiciSubjekty(List<AngazovanySubjektRzp> souvisejiciSubjekty) {
    
    this.souvisejiciSubjekty = souvisejiciSubjekty;
    return this;
  }

  public ZaznamRzpAllOf addSouvisejiciSubjektyItem(AngazovanySubjektRzp souvisejiciSubjektyItem) {
    if (this.souvisejiciSubjekty == null) {
      this.souvisejiciSubjekty = new ArrayList<>();
    }
    this.souvisejiciSubjekty.add(souvisejiciSubjektyItem);
    return this;
  }

   /**
   * Get souvisejiciSubjekty
   * @return souvisejiciSubjekty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AngazovanySubjektRzp> getSouvisejiciSubjekty() {
    return souvisejiciSubjekty;
  }


  public void setSouvisejiciSubjekty(List<AngazovanySubjektRzp> souvisejiciSubjekty) {
    this.souvisejiciSubjekty = souvisejiciSubjekty;
  }


  public ZaznamRzpAllOf osobaPodnikatel(AngazovanaOsobaRzp osobaPodnikatel) {
    
    this.osobaPodnikatel = osobaPodnikatel;
    return this;
  }

   /**
   * Get osobaPodnikatel
   * @return osobaPodnikatel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AngazovanaOsobaRzp getOsobaPodnikatel() {
    return osobaPodnikatel;
  }


  public void setOsobaPodnikatel(AngazovanaOsobaRzp osobaPodnikatel) {
    this.osobaPodnikatel = osobaPodnikatel;
  }


  public ZaznamRzpAllOf angazovaneOsoby(List<AngazovanaOsobaRzp> angazovaneOsoby) {
    
    this.angazovaneOsoby = angazovaneOsoby;
    return this;
  }

  public ZaznamRzpAllOf addAngazovaneOsobyItem(AngazovanaOsobaRzp angazovaneOsobyItem) {
    if (this.angazovaneOsoby == null) {
      this.angazovaneOsoby = new ArrayList<>();
    }
    this.angazovaneOsoby.add(angazovaneOsobyItem);
    return this;
  }

   /**
   * Get angazovaneOsoby
   * @return angazovaneOsoby
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AngazovanaOsobaRzp> getAngazovaneOsoby() {
    return angazovaneOsoby;
  }


  public void setAngazovaneOsoby(List<AngazovanaOsobaRzp> angazovaneOsoby) {
    this.angazovaneOsoby = angazovaneOsoby;
  }


  public ZaznamRzpAllOf zivnosti(List<Zivnost> zivnosti) {
    
    this.zivnosti = zivnosti;
    return this;
  }

  public ZaznamRzpAllOf addZivnostiItem(Zivnost zivnostiItem) {
    if (this.zivnosti == null) {
      this.zivnosti = new ArrayList<>();
    }
    this.zivnosti.add(zivnostiItem);
    return this;
  }

   /**
   * Get zivnosti
   * @return zivnosti
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Zivnost> getZivnosti() {
    return zivnosti;
  }


  public void setZivnosti(List<Zivnost> zivnosti) {
    this.zivnosti = zivnosti;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZaznamRzpAllOf zaznamRzpAllOf = (ZaznamRzpAllOf) o;
    return Objects.equals(this.souvisejiciSubjekty, zaznamRzpAllOf.souvisejiciSubjekty) &&
        Objects.equals(this.osobaPodnikatel, zaznamRzpAllOf.osobaPodnikatel) &&
        Objects.equals(this.angazovaneOsoby, zaznamRzpAllOf.angazovaneOsoby) &&
        Objects.equals(this.zivnosti, zaznamRzpAllOf.zivnosti);
  }

  @Override
  public int hashCode() {
    return Objects.hash(souvisejiciSubjekty, osobaPodnikatel, angazovaneOsoby, zivnosti);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZaznamRzpAllOf {\n");
    sb.append("    souvisejiciSubjekty: ").append(toIndentedString(souvisejiciSubjekty)).append("\n");
    sb.append("    osobaPodnikatel: ").append(toIndentedString(osobaPodnikatel)).append("\n");
    sb.append("    angazovaneOsoby: ").append(toIndentedString(angazovaneOsoby)).append("\n");
    sb.append("    zivnosti: ").append(toIndentedString(zivnosti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("souvisejiciSubjekty");
    openapiFields.add("osobaPodnikatel");
    openapiFields.add("angazovaneOsoby");
    openapiFields.add("zivnosti");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ZaznamRzpAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ZaznamRzpAllOf.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ZaznamRzpAllOf is not found in the empty JSON string", ZaznamRzpAllOf.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ZaznamRzpAllOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ZaznamRzpAllOf` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("souvisejiciSubjekty") != null && !jsonObj.get("souvisejiciSubjekty").isJsonNull()) {
        JsonArray jsonArraysouvisejiciSubjekty = jsonObj.getAsJsonArray("souvisejiciSubjekty");
        if (jsonArraysouvisejiciSubjekty != null) {
          // ensure the json data is an array
          if (!jsonObj.get("souvisejiciSubjekty").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `souvisejiciSubjekty` to be an array in the JSON string but got `%s`", jsonObj.get("souvisejiciSubjekty").toString()));
          }

          // validate the optional field `souvisejiciSubjekty` (array)
          for (int i = 0; i < jsonArraysouvisejiciSubjekty.size(); i++) {
            AngazovanySubjektRzp.validateJsonObject(jsonArraysouvisejiciSubjekty.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `osobaPodnikatel`
      if (jsonObj.get("osobaPodnikatel") != null && !jsonObj.get("osobaPodnikatel").isJsonNull()) {
        AngazovanaOsobaRzp.validateJsonObject(jsonObj.getAsJsonObject("osobaPodnikatel"));
      }
      if (jsonObj.get("angazovaneOsoby") != null && !jsonObj.get("angazovaneOsoby").isJsonNull()) {
        JsonArray jsonArrayangazovaneOsoby = jsonObj.getAsJsonArray("angazovaneOsoby");
        if (jsonArrayangazovaneOsoby != null) {
          // ensure the json data is an array
          if (!jsonObj.get("angazovaneOsoby").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `angazovaneOsoby` to be an array in the JSON string but got `%s`", jsonObj.get("angazovaneOsoby").toString()));
          }

          // validate the optional field `angazovaneOsoby` (array)
          for (int i = 0; i < jsonArrayangazovaneOsoby.size(); i++) {
            AngazovanaOsobaRzp.validateJsonObject(jsonArrayangazovaneOsoby.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("zivnosti") != null && !jsonObj.get("zivnosti").isJsonNull()) {
        JsonArray jsonArrayzivnosti = jsonObj.getAsJsonArray("zivnosti");
        if (jsonArrayzivnosti != null) {
          // ensure the json data is an array
          if (!jsonObj.get("zivnosti").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `zivnosti` to be an array in the JSON string but got `%s`", jsonObj.get("zivnosti").toString()));
          }

          // validate the optional field `zivnosti` (array)
          for (int i = 0; i < jsonArrayzivnosti.size(); i++) {
            Zivnost.validateJsonObject(jsonArrayzivnosti.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ZaznamRzpAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ZaznamRzpAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ZaznamRzpAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ZaznamRzpAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<ZaznamRzpAllOf>() {
           @Override
           public void write(JsonWriter out, ZaznamRzpAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ZaznamRzpAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ZaznamRzpAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ZaznamRzpAllOf
  * @throws IOException if the JSON string is invalid with respect to ZaznamRzpAllOf
  */
  public static ZaznamRzpAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ZaznamRzpAllOf.class);
  }

 /**
  * Convert an instance of ZaznamRzpAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

