/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.EkonomickySubjektRzpAdresa;
import org.openapitools.client.model.InsolvencniRizeni;
import org.openapitools.client.model.ProvozovnyRzpStav;
import org.openapitools.client.model.ZivnostiRzpStav;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ZaznamRzpZakladAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-27T00:34:55.679880400+01:00[Europe/Prague]")
public class ZaznamRzpZakladAllOf {
  public static final String SERIALIZED_NAME_INSOLVENCNI_RIZENI = "insolvencniRizeni";
  @SerializedName(SERIALIZED_NAME_INSOLVENCNI_RIZENI)
  private InsolvencniRizeni insolvencniRizeni;

  public static final String SERIALIZED_NAME_DATUM_DORUCENI_VYPISU = "datumDoruceniVypisu";
  @SerializedName(SERIALIZED_NAME_DATUM_DORUCENI_VYPISU)
  private LocalDate datumDoruceniVypisu;

  public static final String SERIALIZED_NAME_ADRESY_SUBJEKTU = "adresySubjektu";
  @SerializedName(SERIALIZED_NAME_ADRESY_SUBJEKTU)
  private List<EkonomickySubjektRzpAdresa> adresySubjektu = null;

  public static final String SERIALIZED_NAME_TYP_SUBJEKTU = "typSubjektu";
  @SerializedName(SERIALIZED_NAME_TYP_SUBJEKTU)
  private String typSubjektu;

  public static final String SERIALIZED_NAME_ZIVNOSTENSKY_URAD = "zivnostenskyUrad";
  @SerializedName(SERIALIZED_NAME_ZIVNOSTENSKY_URAD)
  private String zivnostenskyUrad;

  public static final String SERIALIZED_NAME_ORGANIZACNI_SLOZKA = "organizacniSlozka";
  @SerializedName(SERIALIZED_NAME_ORGANIZACNI_SLOZKA)
  private String organizacniSlozka;

  public static final String SERIALIZED_NAME_ZIVNOSTI_STAV = "zivnostiStav";
  @SerializedName(SERIALIZED_NAME_ZIVNOSTI_STAV)
  private ZivnostiRzpStav zivnostiStav;

  public static final String SERIALIZED_NAME_DATUM_ZAPISU_VR = "datumZapisuVr";
  @SerializedName(SERIALIZED_NAME_DATUM_ZAPISU_VR)
  private LocalDate datumZapisuVr;

  public static final String SERIALIZED_NAME_PROVOZOVNY_STAV = "provozovnyStav";
  @SerializedName(SERIALIZED_NAME_PROVOZOVNY_STAV)
  private ProvozovnyRzpStav provozovnyStav;

  public static final String SERIALIZED_NAME_PRIMARNI_ZAZNAM = "primarniZaznam";
  @SerializedName(SERIALIZED_NAME_PRIMARNI_ZAZNAM)
  private Boolean primarniZaznam;

  public static final String SERIALIZED_NAME_KOD_STATU = "kodStatu";
  @SerializedName(SERIALIZED_NAME_KOD_STATU)
  private String kodStatu;

  public ZaznamRzpZakladAllOf() {
  }

  public ZaznamRzpZakladAllOf insolvencniRizeni(InsolvencniRizeni insolvencniRizeni) {
    
    this.insolvencniRizeni = insolvencniRizeni;
    return this;
  }

   /**
   * Get insolvencniRizeni
   * @return insolvencniRizeni
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InsolvencniRizeni getInsolvencniRizeni() {
    return insolvencniRizeni;
  }


  public void setInsolvencniRizeni(InsolvencniRizeni insolvencniRizeni) {
    this.insolvencniRizeni = insolvencniRizeni;
  }


  public ZaznamRzpZakladAllOf datumDoruceniVypisu(LocalDate datumDoruceniVypisu) {
    
    this.datumDoruceniVypisu = datumDoruceniVypisu;
    return this;
  }

   /**
   * Datum doručení prvního výpisu sloužícího jako průkaz živnostenského podnikání, 
   * @return datumDoruceniVypisu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum doručení prvního výpisu sloužícího jako průkaz živnostenského podnikání, ")

  public LocalDate getDatumDoruceniVypisu() {
    return datumDoruceniVypisu;
  }


  public void setDatumDoruceniVypisu(LocalDate datumDoruceniVypisu) {
    this.datumDoruceniVypisu = datumDoruceniVypisu;
  }


  public ZaznamRzpZakladAllOf adresySubjektu(List<EkonomickySubjektRzpAdresa> adresySubjektu) {
    
    this.adresySubjektu = adresySubjektu;
    return this;
  }

  public ZaznamRzpZakladAllOf addAdresySubjektuItem(EkonomickySubjektRzpAdresa adresySubjektuItem) {
    if (this.adresySubjektu == null) {
      this.adresySubjektu = new ArrayList<>();
    }
    this.adresySubjektu.add(adresySubjektuItem);
    return this;
  }

   /**
   * Get adresySubjektu
   * @return adresySubjektu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<EkonomickySubjektRzpAdresa> getAdresySubjektu() {
    return adresySubjektu;
  }


  public void setAdresySubjektu(List<EkonomickySubjektRzpAdresa> adresySubjektu) {
    this.adresySubjektu = adresySubjektu;
  }


  public ZaznamRzpZakladAllOf typSubjektu(String typSubjektu) {
    
    this.typSubjektu = typSubjektu;
    return this;
  }

   /**
   * Typ subjektu - kód (ciselnikKod: TypSubjektu, zdroj: rzp) 
   * @return typSubjektu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Typ subjektu - kód (ciselnikKod: TypSubjektu, zdroj: rzp) ")

  public String getTypSubjektu() {
    return typSubjektu;
  }


  public void setTypSubjektu(String typSubjektu) {
    this.typSubjektu = typSubjektu;
  }


  public ZaznamRzpZakladAllOf zivnostenskyUrad(String zivnostenskyUrad) {
    
    this.zivnostenskyUrad = zivnostenskyUrad;
    return this;
  }

   /**
   * Živnostenský úřadu - kód
   * @return zivnostenskyUrad
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Živnostenský úřadu - kód")

  public String getZivnostenskyUrad() {
    return zivnostenskyUrad;
  }


  public void setZivnostenskyUrad(String zivnostenskyUrad) {
    this.zivnostenskyUrad = zivnostenskyUrad;
  }


  public ZaznamRzpZakladAllOf organizacniSlozka(String organizacniSlozka) {
    
    this.organizacniSlozka = organizacniSlozka;
    return this;
  }

   /**
   * Název organizační složky
   * @return organizacniSlozka
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Název organizační složky")

  public String getOrganizacniSlozka() {
    return organizacniSlozka;
  }


  public void setOrganizacniSlozka(String organizacniSlozka) {
    this.organizacniSlozka = organizacniSlozka;
  }


  public ZaznamRzpZakladAllOf zivnostiStav(ZivnostiRzpStav zivnostiStav) {
    
    this.zivnostiStav = zivnostiStav;
    return this;
  }

   /**
   * Get zivnostiStav
   * @return zivnostiStav
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ZivnostiRzpStav getZivnostiStav() {
    return zivnostiStav;
  }


  public void setZivnostiStav(ZivnostiRzpStav zivnostiStav) {
    this.zivnostiStav = zivnostiStav;
  }


  public ZaznamRzpZakladAllOf datumZapisuVr(LocalDate datumZapisuVr) {
    
    this.datumZapisuVr = datumZapisuVr;
    return this;
  }

   /**
   * Datum zápisu do Obchodního nebo podobného rejstříku 
   * @return datumZapisuVr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum zápisu do Obchodního nebo podobného rejstříku ")

  public LocalDate getDatumZapisuVr() {
    return datumZapisuVr;
  }


  public void setDatumZapisuVr(LocalDate datumZapisuVr) {
    this.datumZapisuVr = datumZapisuVr;
  }


  public ZaznamRzpZakladAllOf provozovnyStav(ProvozovnyRzpStav provozovnyStav) {
    
    this.provozovnyStav = provozovnyStav;
    return this;
  }

   /**
   * Get provozovnyStav
   * @return provozovnyStav
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProvozovnyRzpStav getProvozovnyStav() {
    return provozovnyStav;
  }


  public void setProvozovnyStav(ProvozovnyRzpStav provozovnyStav) {
    this.provozovnyStav = provozovnyStav;
  }


  public ZaznamRzpZakladAllOf primarniZaznam(Boolean primarniZaznam) {
    
    this.primarniZaznam = primarniZaznam;
    return this;
  }

   /**
   * Identifikace primárního záznamu  pozn.: U multiplicitních registrací je pouze jedna registrace primární
   * @return primarniZaznam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifikace primárního záznamu  pozn.: U multiplicitních registrací je pouze jedna registrace primární")

  public Boolean getPrimarniZaznam() {
    return primarniZaznam;
  }


  public void setPrimarniZaznam(Boolean primarniZaznam) {
    this.primarniZaznam = primarniZaznam;
  }


  public ZaznamRzpZakladAllOf kodStatu(String kodStatu) {
    
    this.kodStatu = kodStatu;
    return this;
  }

   /**
   * Kód státu  (ciselnikKod: Stat, zdroj:com) 
   * @return kodStatu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kód státu  (ciselnikKod: Stat, zdroj:com) ")

  public String getKodStatu() {
    return kodStatu;
  }


  public void setKodStatu(String kodStatu) {
    this.kodStatu = kodStatu;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZaznamRzpZakladAllOf zaznamRzpZakladAllOf = (ZaznamRzpZakladAllOf) o;
    return Objects.equals(this.insolvencniRizeni, zaznamRzpZakladAllOf.insolvencniRizeni) &&
        Objects.equals(this.datumDoruceniVypisu, zaznamRzpZakladAllOf.datumDoruceniVypisu) &&
        Objects.equals(this.adresySubjektu, zaznamRzpZakladAllOf.adresySubjektu) &&
        Objects.equals(this.typSubjektu, zaznamRzpZakladAllOf.typSubjektu) &&
        Objects.equals(this.zivnostenskyUrad, zaznamRzpZakladAllOf.zivnostenskyUrad) &&
        Objects.equals(this.organizacniSlozka, zaznamRzpZakladAllOf.organizacniSlozka) &&
        Objects.equals(this.zivnostiStav, zaznamRzpZakladAllOf.zivnostiStav) &&
        Objects.equals(this.datumZapisuVr, zaznamRzpZakladAllOf.datumZapisuVr) &&
        Objects.equals(this.provozovnyStav, zaznamRzpZakladAllOf.provozovnyStav) &&
        Objects.equals(this.primarniZaznam, zaznamRzpZakladAllOf.primarniZaznam) &&
        Objects.equals(this.kodStatu, zaznamRzpZakladAllOf.kodStatu);
  }

  @Override
  public int hashCode() {
    return Objects.hash(insolvencniRizeni, datumDoruceniVypisu, adresySubjektu, typSubjektu, zivnostenskyUrad, organizacniSlozka, zivnostiStav, datumZapisuVr, provozovnyStav, primarniZaznam, kodStatu);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZaznamRzpZakladAllOf {\n");
    sb.append("    insolvencniRizeni: ").append(toIndentedString(insolvencniRizeni)).append("\n");
    sb.append("    datumDoruceniVypisu: ").append(toIndentedString(datumDoruceniVypisu)).append("\n");
    sb.append("    adresySubjektu: ").append(toIndentedString(adresySubjektu)).append("\n");
    sb.append("    typSubjektu: ").append(toIndentedString(typSubjektu)).append("\n");
    sb.append("    zivnostenskyUrad: ").append(toIndentedString(zivnostenskyUrad)).append("\n");
    sb.append("    organizacniSlozka: ").append(toIndentedString(organizacniSlozka)).append("\n");
    sb.append("    zivnostiStav: ").append(toIndentedString(zivnostiStav)).append("\n");
    sb.append("    datumZapisuVr: ").append(toIndentedString(datumZapisuVr)).append("\n");
    sb.append("    provozovnyStav: ").append(toIndentedString(provozovnyStav)).append("\n");
    sb.append("    primarniZaznam: ").append(toIndentedString(primarniZaznam)).append("\n");
    sb.append("    kodStatu: ").append(toIndentedString(kodStatu)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("insolvencniRizeni");
    openapiFields.add("datumDoruceniVypisu");
    openapiFields.add("adresySubjektu");
    openapiFields.add("typSubjektu");
    openapiFields.add("zivnostenskyUrad");
    openapiFields.add("organizacniSlozka");
    openapiFields.add("zivnostiStav");
    openapiFields.add("datumZapisuVr");
    openapiFields.add("provozovnyStav");
    openapiFields.add("primarniZaznam");
    openapiFields.add("kodStatu");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ZaznamRzpZakladAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ZaznamRzpZakladAllOf.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ZaznamRzpZakladAllOf is not found in the empty JSON string", ZaznamRzpZakladAllOf.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ZaznamRzpZakladAllOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ZaznamRzpZakladAllOf` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `insolvencniRizeni`
      if (jsonObj.get("insolvencniRizeni") != null && !jsonObj.get("insolvencniRizeni").isJsonNull()) {
        InsolvencniRizeni.validateJsonObject(jsonObj.getAsJsonObject("insolvencniRizeni"));
      }
      if (jsonObj.get("adresySubjektu") != null && !jsonObj.get("adresySubjektu").isJsonNull()) {
        JsonArray jsonArrayadresySubjektu = jsonObj.getAsJsonArray("adresySubjektu");
        if (jsonArrayadresySubjektu != null) {
          // ensure the json data is an array
          if (!jsonObj.get("adresySubjektu").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `adresySubjektu` to be an array in the JSON string but got `%s`", jsonObj.get("adresySubjektu").toString()));
          }

          // validate the optional field `adresySubjektu` (array)
          for (int i = 0; i < jsonArrayadresySubjektu.size(); i++) {
            EkonomickySubjektRzpAdresa.validateJsonObject(jsonArrayadresySubjektu.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("typSubjektu") != null && !jsonObj.get("typSubjektu").isJsonNull()) && !jsonObj.get("typSubjektu").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typSubjektu` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typSubjektu").toString()));
      }
      if ((jsonObj.get("zivnostenskyUrad") != null && !jsonObj.get("zivnostenskyUrad").isJsonNull()) && !jsonObj.get("zivnostenskyUrad").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `zivnostenskyUrad` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zivnostenskyUrad").toString()));
      }
      if ((jsonObj.get("organizacniSlozka") != null && !jsonObj.get("organizacniSlozka").isJsonNull()) && !jsonObj.get("organizacniSlozka").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organizacniSlozka` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organizacniSlozka").toString()));
      }
      // validate the optional field `zivnostiStav`
      if (jsonObj.get("zivnostiStav") != null && !jsonObj.get("zivnostiStav").isJsonNull()) {
        ZivnostiRzpStav.validateJsonObject(jsonObj.getAsJsonObject("zivnostiStav"));
      }
      // validate the optional field `provozovnyStav`
      if (jsonObj.get("provozovnyStav") != null && !jsonObj.get("provozovnyStav").isJsonNull()) {
        ProvozovnyRzpStav.validateJsonObject(jsonObj.getAsJsonObject("provozovnyStav"));
      }
      if ((jsonObj.get("kodStatu") != null && !jsonObj.get("kodStatu").isJsonNull()) && !jsonObj.get("kodStatu").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kodStatu` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kodStatu").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ZaznamRzpZakladAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ZaznamRzpZakladAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ZaznamRzpZakladAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ZaznamRzpZakladAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<ZaznamRzpZakladAllOf>() {
           @Override
           public void write(JsonWriter out, ZaznamRzpZakladAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ZaznamRzpZakladAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ZaznamRzpZakladAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ZaznamRzpZakladAllOf
  * @throws IOException if the JSON string is invalid with respect to ZaznamRzpZakladAllOf
  */
  public static ZaznamRzpZakladAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ZaznamRzpZakladAllOf.class);
  }

 /**
  * Convert an instance of ZaznamRzpZakladAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

