/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Detailní informace o ekonomickém subjektu ze zdroje CEÚ
 */
@ApiModel(description = "Detailní informace o ekonomickém subjektu ze zdroje CEÚ")
@JsonPropertyOrder({
  ZaznamCeu.JSON_PROPERTY_ICO,
  ZaznamCeu.JSON_PROPERTY_OBCHODNI_JMENO,
  ZaznamCeu.JSON_PROPERTY_SIDLO,
  ZaznamCeu.JSON_PROPERTY_PRAVNI_FORMA,
  ZaznamCeu.JSON_PROPERTY_FINANCNI_URAD,
  ZaznamCeu.JSON_PROPERTY_DATUM_VZNIKU,
  ZaznamCeu.JSON_PROPERTY_DATUM_ZANIKU,
  ZaznamCeu.JSON_PROPERTY_DATUM_AKTUALIZACE,
  ZaznamCeu.JSON_PROPERTY_DIC,
  ZaznamCeu.JSON_PROPERTY_TYP_SUBJEKTU,
  ZaznamCeu.JSON_PROPERTY_ADRESY,
  ZaznamCeu.JSON_PROPERTY_JMENO_PRIJMENI,
  ZaznamCeu.JSON_PROPERTY_UPADEK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-07T00:05:51.802385700+01:00[Europe/Prague]")
public class ZaznamCeu {
  public static final String JSON_PROPERTY_ICO = "ico";
  private String ico;

  public static final String JSON_PROPERTY_OBCHODNI_JMENO = "obchodniJmeno";
  private String obchodniJmeno;

  public static final String JSON_PROPERTY_SIDLO = "sidlo";
  private Adresa sidlo;

  public static final String JSON_PROPERTY_PRAVNI_FORMA = "pravniForma";
  private String pravniForma;

  public static final String JSON_PROPERTY_FINANCNI_URAD = "financniUrad";
  private String financniUrad;

  public static final String JSON_PROPERTY_DATUM_VZNIKU = "datumVzniku";
  private LocalDate datumVzniku;

  public static final String JSON_PROPERTY_DATUM_ZANIKU = "datumZaniku";
  private LocalDate datumZaniku;

  public static final String JSON_PROPERTY_DATUM_AKTUALIZACE = "datumAktualizace";
  private LocalDate datumAktualizace;

  public static final String JSON_PROPERTY_DIC = "dic";
  private String dic;

  public static final String JSON_PROPERTY_TYP_SUBJEKTU = "typSubjektu";
  private String typSubjektu;

  public static final String JSON_PROPERTY_ADRESY = "adresy";
  private List<AdresaCeu> adresy = null;

  public static final String JSON_PROPERTY_JMENO_PRIJMENI = "jmenoPrijmeni";
  private String jmenoPrijmeni;

  public static final String JSON_PROPERTY_UPADEK = "upadek";
  private List<UpadekCeuVerejny> upadek = null;

  public ZaznamCeu() {
  }

  public ZaznamCeu ico(String ico) {
    
    this.ico = ico;
    return this;
  }

   /**
   * Identifikační číslo osoby - IČO
   * @return ico
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifikační číslo osoby - IČO")
  @JsonProperty(JSON_PROPERTY_ICO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIco() {
    return ico;
  }


  @JsonProperty(JSON_PROPERTY_ICO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIco(String ico) {
    this.ico = ico;
  }


  public ZaznamCeu obchodniJmeno(String obchodniJmeno) {
    
    this.obchodniJmeno = obchodniJmeno;
    return this;
  }

   /**
   * Obchodní jméno ekonomického subjektu
   * @return obchodniJmeno
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Obchodní jméno ekonomického subjektu")
  @JsonProperty(JSON_PROPERTY_OBCHODNI_JMENO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getObchodniJmeno() {
    return obchodniJmeno;
  }


  @JsonProperty(JSON_PROPERTY_OBCHODNI_JMENO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObchodniJmeno(String obchodniJmeno) {
    this.obchodniJmeno = obchodniJmeno;
  }


  public ZaznamCeu sidlo(Adresa sidlo) {
    
    this.sidlo = sidlo;
    return this;
  }

   /**
   * Get sidlo
   * @return sidlo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIDLO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Adresa getSidlo() {
    return sidlo;
  }


  @JsonProperty(JSON_PROPERTY_SIDLO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSidlo(Adresa sidlo) {
    this.sidlo = sidlo;
  }


  public ZaznamCeu pravniForma(String pravniForma) {
    
    this.pravniForma = pravniForma;
    return this;
  }

   /**
   * Právní forma - kód (ciselnikKod: PravniForma, zdroj: res, com) 
   * @return pravniForma
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Právní forma - kód (ciselnikKod: PravniForma, zdroj: res, com) ")
  @JsonProperty(JSON_PROPERTY_PRAVNI_FORMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPravniForma() {
    return pravniForma;
  }


  @JsonProperty(JSON_PROPERTY_PRAVNI_FORMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPravniForma(String pravniForma) {
    this.pravniForma = pravniForma;
  }


  public ZaznamCeu financniUrad(String financniUrad) {
    
    this.financniUrad = financniUrad;
    return this;
  }

   /**
   * Správně příslušný finanční úřad - kód (ciselnikKod: FinancniUrad, zdroj:ufo) 
   * @return financniUrad
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Správně příslušný finanční úřad - kód (ciselnikKod: FinancniUrad, zdroj:ufo) ")
  @JsonProperty(JSON_PROPERTY_FINANCNI_URAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFinancniUrad() {
    return financniUrad;
  }


  @JsonProperty(JSON_PROPERTY_FINANCNI_URAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancniUrad(String financniUrad) {
    this.financniUrad = financniUrad;
  }


  public ZaznamCeu datumVzniku(LocalDate datumVzniku) {
    
    this.datumVzniku = datumVzniku;
    return this;
  }

   /**
   * Datum vzniku ekonomického subjektu 
   * @return datumVzniku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum vzniku ekonomického subjektu ")
  @JsonProperty(JSON_PROPERTY_DATUM_VZNIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumVzniku() {
    return datumVzniku;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_VZNIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumVzniku(LocalDate datumVzniku) {
    this.datumVzniku = datumVzniku;
  }


  public ZaznamCeu datumZaniku(LocalDate datumZaniku) {
    
    this.datumZaniku = datumZaniku;
    return this;
  }

   /**
   * Datum zániku ekonomického subjektu
   * @return datumZaniku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum zániku ekonomického subjektu")
  @JsonProperty(JSON_PROPERTY_DATUM_ZANIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumZaniku() {
    return datumZaniku;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_ZANIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumZaniku(LocalDate datumZaniku) {
    this.datumZaniku = datumZaniku;
  }


  public ZaznamCeu datumAktualizace(LocalDate datumAktualizace) {
    
    this.datumAktualizace = datumAktualizace;
    return this;
  }

   /**
   * Datum aktualizace záznamu
   * @return datumAktualizace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum aktualizace záznamu")
  @JsonProperty(JSON_PROPERTY_DATUM_AKTUALIZACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumAktualizace() {
    return datumAktualizace;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_AKTUALIZACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumAktualizace(LocalDate datumAktualizace) {
    this.datumAktualizace = datumAktualizace;
  }


  public ZaznamCeu dic(String dic) {
    
    this.dic = dic;
    return this;
  }

   /**
   * Daňové identifikační číslo ve formátu CZNNNNNNNNNN
   * @return dic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Daňové identifikační číslo ve formátu CZNNNNNNNNNN")
  @JsonProperty(JSON_PROPERTY_DIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDic() {
    return dic;
  }


  @JsonProperty(JSON_PROPERTY_DIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDic(String dic) {
    this.dic = dic;
  }


  public ZaznamCeu typSubjektu(String typSubjektu) {
    
    this.typSubjektu = typSubjektu;
    return this;
  }

   /**
   * Typ subjektu  (ciselnikKod: TypSubjektu, zdroj: Ceu) 
   * @return typSubjektu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Typ subjektu  (ciselnikKod: TypSubjektu, zdroj: Ceu) ")
  @JsonProperty(JSON_PROPERTY_TYP_SUBJEKTU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypSubjektu() {
    return typSubjektu;
  }


  @JsonProperty(JSON_PROPERTY_TYP_SUBJEKTU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypSubjektu(String typSubjektu) {
    this.typSubjektu = typSubjektu;
  }


  public ZaznamCeu adresy(List<AdresaCeu> adresy) {
    
    this.adresy = adresy;
    return this;
  }

  public ZaznamCeu addAdresyItem(AdresaCeu adresyItem) {
    if (this.adresy == null) {
      this.adresy = new ArrayList<>();
    }
    this.adresy.add(adresyItem);
    return this;
  }

   /**
   * Get adresy
   * @return adresy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADRESY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdresaCeu> getAdresy() {
    return adresy;
  }


  @JsonProperty(JSON_PROPERTY_ADRESY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdresy(List<AdresaCeu> adresy) {
    this.adresy = adresy;
  }


  public ZaznamCeu jmenoPrijmeni(String jmenoPrijmeni) {
    
    this.jmenoPrijmeni = jmenoPrijmeni;
    return this;
  }

   /**
   * Jméno, příjmení fyzické osoby
   * @return jmenoPrijmeni
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Jméno, příjmení fyzické osoby")
  @JsonProperty(JSON_PROPERTY_JMENO_PRIJMENI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJmenoPrijmeni() {
    return jmenoPrijmeni;
  }


  @JsonProperty(JSON_PROPERTY_JMENO_PRIJMENI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJmenoPrijmeni(String jmenoPrijmeni) {
    this.jmenoPrijmeni = jmenoPrijmeni;
  }


  public ZaznamCeu upadek(List<UpadekCeuVerejny> upadek) {
    
    this.upadek = upadek;
    return this;
  }

  public ZaznamCeu addUpadekItem(UpadekCeuVerejny upadekItem) {
    if (this.upadek == null) {
      this.upadek = new ArrayList<>();
    }
    this.upadek.add(upadekItem);
    return this;
  }

   /**
   * Get upadek
   * @return upadek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPADEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpadekCeuVerejny> getUpadek() {
    return upadek;
  }


  @JsonProperty(JSON_PROPERTY_UPADEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpadek(List<UpadekCeuVerejny> upadek) {
    this.upadek = upadek;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZaznamCeu zaznamCeu = (ZaznamCeu) o;
    return Objects.equals(this.ico, zaznamCeu.ico) &&
        Objects.equals(this.obchodniJmeno, zaznamCeu.obchodniJmeno) &&
        Objects.equals(this.sidlo, zaznamCeu.sidlo) &&
        Objects.equals(this.pravniForma, zaznamCeu.pravniForma) &&
        Objects.equals(this.financniUrad, zaznamCeu.financniUrad) &&
        Objects.equals(this.datumVzniku, zaznamCeu.datumVzniku) &&
        Objects.equals(this.datumZaniku, zaznamCeu.datumZaniku) &&
        Objects.equals(this.datumAktualizace, zaznamCeu.datumAktualizace) &&
        Objects.equals(this.dic, zaznamCeu.dic) &&
        Objects.equals(this.typSubjektu, zaznamCeu.typSubjektu) &&
        Objects.equals(this.adresy, zaznamCeu.adresy) &&
        Objects.equals(this.jmenoPrijmeni, zaznamCeu.jmenoPrijmeni) &&
        Objects.equals(this.upadek, zaznamCeu.upadek);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ico, obchodniJmeno, sidlo, pravniForma, financniUrad, datumVzniku, datumZaniku, datumAktualizace, dic, typSubjektu, adresy, jmenoPrijmeni, upadek);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZaznamCeu {\n");
    sb.append("    ico: ").append(toIndentedString(ico)).append("\n");
    sb.append("    obchodniJmeno: ").append(toIndentedString(obchodniJmeno)).append("\n");
    sb.append("    sidlo: ").append(toIndentedString(sidlo)).append("\n");
    sb.append("    pravniForma: ").append(toIndentedString(pravniForma)).append("\n");
    sb.append("    financniUrad: ").append(toIndentedString(financniUrad)).append("\n");
    sb.append("    datumVzniku: ").append(toIndentedString(datumVzniku)).append("\n");
    sb.append("    datumZaniku: ").append(toIndentedString(datumZaniku)).append("\n");
    sb.append("    datumAktualizace: ").append(toIndentedString(datumAktualizace)).append("\n");
    sb.append("    dic: ").append(toIndentedString(dic)).append("\n");
    sb.append("    typSubjektu: ").append(toIndentedString(typSubjektu)).append("\n");
    sb.append("    adresy: ").append(toIndentedString(adresy)).append("\n");
    sb.append("    jmenoPrijmeni: ").append(toIndentedString(jmenoPrijmeni)).append("\n");
    sb.append("    upadek: ").append(toIndentedString(upadek)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

