/*
 * ARES: REST API - veřejné
 * generováno: čtvrtek 14. prosince 2023 14:19:28, použité package:<<REST_COMMON>> DTO_COMMON,<<REST_COMMON_STRANKOVANI>> Řazení a stránkování,<<REST_COMMON_TEC>> Technické,<<REST_COMMON_TYPY>> DATOVE_TYPY_COMMON,<<REST_ARES>> EkonomickeSubjektySluzba,<<REST_ARES_DTO_COMMON>> DTO_ARES_COMMON,<<REST_VR>> EkonomickeSubjektyVrSluzba,<<REST_VR_DTO>> DTO_VR,<<REST_VR_DTO_COMMON>> DTO_VR_COMMON,<<REST_RES>> EkonomickeSubjektyResSluzba,<<REST_RES_DTO_COMMON>> DTO_RES_COMMON,<<REST_RZP>> EkonomickeSubjektyRzpSluzba,<<REST_RZP_DTO_COMMON>> DTO_RZP_COMMON,<<REST_RZP_DTO>> DTO_RZP,<<REST_NRPZS>> EkonomickeSubjektyNrpzsSluzba,<<REST_NRPZS_DTO_COMMON>> DTO_NRPZS_COMMON,<<REST_RPSH>> EkonomickeSubjektyRpshSluzba,<<REST_RPSH_DTO_COMMON>> DTO_RPSH_COMMON,<<REST_RCNS>> EkonomickeSubjektyRcnsSluzba,<<REST_RCNS_DTO_COMMON>> DTO_RCNS_COMMON,<<REST_RCNS_DTO>> DTO_RCNS,<<REST_SZR>> EkonomickeSubjektySzrSluzba,<<REST_SZR_DTO_COMMON>> REST_SZR_DTO_COMMON,<<REST_SZR_DTO>> DTO_SZR,<<REST_RS>> EkonomickeSubjektyRsSluzba,<<REST_RS_DTO_COMMON>> DTO_RS_COMMON,<<REST_RS_DTO>> DTO_RS,<<REST_CIS>> CiselnikyNazevnikySluzba,<<REST_CIS_DTO_COMMON>> DTO_CIS_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL,<<REST_RUIAN>> StandardizovaneAdresySluzba,<<REST_RUIAN_DTO_COMMON>> DTO_RUIAN_COMMON,<<REST_CEU>> EkonomickeSubjektyCeuSluzba,<<REST_CEU_DTO_COMMON>> REST_CEU_DTO_COMMON,<<REST_CEU_DTO>> DTO_CEU,<<REST_NOTIFIKACE>> EkonomickeSubjektyNotifikaceSluzba,<<REST_NOTIFIKACE_DTO_COMMON>> REST_NOTIFIKACE_DTO_COMMON,<<REST_DETAIL>> DTO_COMMON_DETAIL_NEV
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Živnosti, které ekonomický subjekt provozuje nebo provozoval
 */
@ApiModel(description = "Živnosti, které ekonomický subjekt provozuje nebo provozoval")
@JsonPropertyOrder({
  ZivnostZaklad.JSON_PROPERTY_DATUM_VZNIKU,
  ZivnostZaklad.JSON_PROPERTY_DATUM_ZANIKU,
  ZivnostZaklad.JSON_PROPERTY_PLATNOST_DO,
  ZivnostZaklad.JSON_PROPERTY_PREDMET_PODNIKANI,
  ZivnostZaklad.JSON_PROPERTY_POZASTAVENI_ZIVNOSTI,
  ZivnostZaklad.JSON_PROPERTY_PODMINKY_PROVOZOVANI_ZIVNOSTI,
  ZivnostZaklad.JSON_PROPERTY_PRERUSENI_ZIVNOSTI,
  ZivnostZaklad.JSON_PROPERTY_ZIVNOST_BEZ_OZ,
  ZivnostZaklad.JSON_PROPERTY_DATUM_AKTUALIZACE,
  ZivnostZaklad.JSON_PROPERTY_DRUH_ZIVNOSTI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-07T00:05:51.802385700+01:00[Europe/Prague]")
public class ZivnostZaklad {
  public static final String JSON_PROPERTY_DATUM_VZNIKU = "datumVzniku";
  private LocalDate datumVzniku;

  public static final String JSON_PROPERTY_DATUM_ZANIKU = "datumZaniku";
  private LocalDate datumZaniku;

  public static final String JSON_PROPERTY_PLATNOST_DO = "platnostDo";
  private LocalDate platnostDo;

  public static final String JSON_PROPERTY_PREDMET_PODNIKANI = "predmetPodnikani";
  private String predmetPodnikani;

  public static final String JSON_PROPERTY_POZASTAVENI_ZIVNOSTI = "pozastaveniZivnosti";
  private List<ZivnostProvozovnaPozastaveni> pozastaveniZivnosti = null;

  public static final String JSON_PROPERTY_PODMINKY_PROVOZOVANI_ZIVNOSTI = "podminkyProvozovaniZivnosti";
  private List<ZivnostPodminky> podminkyProvozovaniZivnosti = null;

  public static final String JSON_PROPERTY_PRERUSENI_ZIVNOSTI = "preruseniZivnosti";
  private List<ZivnostPreruseni> preruseniZivnosti = null;

  public static final String JSON_PROPERTY_ZIVNOST_BEZ_OZ = "zivnostBezOz";
  private List<ZivnostBezOZ> zivnostBezOz = null;

  public static final String JSON_PROPERTY_DATUM_AKTUALIZACE = "datumAktualizace";
  private LocalDate datumAktualizace;

  public static final String JSON_PROPERTY_DRUH_ZIVNOSTI = "druhZivnosti";
  private String druhZivnosti;

  public ZivnostZaklad() {
  }

  public ZivnostZaklad datumVzniku(LocalDate datumVzniku) {
    
    this.datumVzniku = datumVzniku;
    return this;
  }

   /**
   * Datum vzniku živnosti 
   * @return datumVzniku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum vzniku živnosti ")
  @JsonProperty(JSON_PROPERTY_DATUM_VZNIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumVzniku() {
    return datumVzniku;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_VZNIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumVzniku(LocalDate datumVzniku) {
    this.datumVzniku = datumVzniku;
  }


  public ZivnostZaklad datumZaniku(LocalDate datumZaniku) {
    
    this.datumZaniku = datumZaniku;
    return this;
  }

   /**
   * Datum zániku živnosti 
   * @return datumZaniku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum zániku živnosti ")
  @JsonProperty(JSON_PROPERTY_DATUM_ZANIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumZaniku() {
    return datumZaniku;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_ZANIKU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumZaniku(LocalDate datumZaniku) {
    this.datumZaniku = datumZaniku;
  }


  public ZivnostZaklad platnostDo(LocalDate platnostDo) {
    
    this.platnostDo = platnostDo;
    return this;
  }

   /**
   * Platnost živnosti do data
   * @return platnostDo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Platnost živnosti do data")
  @JsonProperty(JSON_PROPERTY_PLATNOST_DO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getPlatnostDo() {
    return platnostDo;
  }


  @JsonProperty(JSON_PROPERTY_PLATNOST_DO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatnostDo(LocalDate platnostDo) {
    this.platnostDo = platnostDo;
  }


  public ZivnostZaklad predmetPodnikani(String predmetPodnikani) {
    
    this.predmetPodnikani = predmetPodnikani;
    return this;
  }

   /**
   * Předmět podnikáni živnosti
   * @return predmetPodnikani
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Předmět podnikáni živnosti")
  @JsonProperty(JSON_PROPERTY_PREDMET_PODNIKANI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPredmetPodnikani() {
    return predmetPodnikani;
  }


  @JsonProperty(JSON_PROPERTY_PREDMET_PODNIKANI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPredmetPodnikani(String predmetPodnikani) {
    this.predmetPodnikani = predmetPodnikani;
  }


  public ZivnostZaklad pozastaveniZivnosti(List<ZivnostProvozovnaPozastaveni> pozastaveniZivnosti) {
    
    this.pozastaveniZivnosti = pozastaveniZivnosti;
    return this;
  }

  public ZivnostZaklad addPozastaveniZivnostiItem(ZivnostProvozovnaPozastaveni pozastaveniZivnostiItem) {
    if (this.pozastaveniZivnosti == null) {
      this.pozastaveniZivnosti = new ArrayList<>();
    }
    this.pozastaveniZivnosti.add(pozastaveniZivnostiItem);
    return this;
  }

   /**
   * Get pozastaveniZivnosti
   * @return pozastaveniZivnosti
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POZASTAVENI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ZivnostProvozovnaPozastaveni> getPozastaveniZivnosti() {
    return pozastaveniZivnosti;
  }


  @JsonProperty(JSON_PROPERTY_POZASTAVENI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPozastaveniZivnosti(List<ZivnostProvozovnaPozastaveni> pozastaveniZivnosti) {
    this.pozastaveniZivnosti = pozastaveniZivnosti;
  }


  public ZivnostZaklad podminkyProvozovaniZivnosti(List<ZivnostPodminky> podminkyProvozovaniZivnosti) {
    
    this.podminkyProvozovaniZivnosti = podminkyProvozovaniZivnosti;
    return this;
  }

  public ZivnostZaklad addPodminkyProvozovaniZivnostiItem(ZivnostPodminky podminkyProvozovaniZivnostiItem) {
    if (this.podminkyProvozovaniZivnosti == null) {
      this.podminkyProvozovaniZivnosti = new ArrayList<>();
    }
    this.podminkyProvozovaniZivnosti.add(podminkyProvozovaniZivnostiItem);
    return this;
  }

   /**
   * Get podminkyProvozovaniZivnosti
   * @return podminkyProvozovaniZivnosti
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PODMINKY_PROVOZOVANI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ZivnostPodminky> getPodminkyProvozovaniZivnosti() {
    return podminkyProvozovaniZivnosti;
  }


  @JsonProperty(JSON_PROPERTY_PODMINKY_PROVOZOVANI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPodminkyProvozovaniZivnosti(List<ZivnostPodminky> podminkyProvozovaniZivnosti) {
    this.podminkyProvozovaniZivnosti = podminkyProvozovaniZivnosti;
  }


  public ZivnostZaklad preruseniZivnosti(List<ZivnostPreruseni> preruseniZivnosti) {
    
    this.preruseniZivnosti = preruseniZivnosti;
    return this;
  }

  public ZivnostZaklad addPreruseniZivnostiItem(ZivnostPreruseni preruseniZivnostiItem) {
    if (this.preruseniZivnosti == null) {
      this.preruseniZivnosti = new ArrayList<>();
    }
    this.preruseniZivnosti.add(preruseniZivnostiItem);
    return this;
  }

   /**
   * Get preruseniZivnosti
   * @return preruseniZivnosti
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRERUSENI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ZivnostPreruseni> getPreruseniZivnosti() {
    return preruseniZivnosti;
  }


  @JsonProperty(JSON_PROPERTY_PRERUSENI_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreruseniZivnosti(List<ZivnostPreruseni> preruseniZivnosti) {
    this.preruseniZivnosti = preruseniZivnosti;
  }


  public ZivnostZaklad zivnostBezOz(List<ZivnostBezOZ> zivnostBezOz) {
    
    this.zivnostBezOz = zivnostBezOz;
    return this;
  }

  public ZivnostZaklad addZivnostBezOzItem(ZivnostBezOZ zivnostBezOzItem) {
    if (this.zivnostBezOz == null) {
      this.zivnostBezOz = new ArrayList<>();
    }
    this.zivnostBezOz.add(zivnostBezOzItem);
    return this;
  }

   /**
   * Get zivnostBezOz
   * @return zivnostBezOz
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ZIVNOST_BEZ_OZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ZivnostBezOZ> getZivnostBezOz() {
    return zivnostBezOz;
  }


  @JsonProperty(JSON_PROPERTY_ZIVNOST_BEZ_OZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZivnostBezOz(List<ZivnostBezOZ> zivnostBezOz) {
    this.zivnostBezOz = zivnostBezOz;
  }


  public ZivnostZaklad datumAktualizace(LocalDate datumAktualizace) {
    
    this.datumAktualizace = datumAktualizace;
    return this;
  }

   /**
   * Datum aktualizace záznamu
   * @return datumAktualizace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Datum aktualizace záznamu")
  @JsonProperty(JSON_PROPERTY_DATUM_AKTUALIZACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDatumAktualizace() {
    return datumAktualizace;
  }


  @JsonProperty(JSON_PROPERTY_DATUM_AKTUALIZACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatumAktualizace(LocalDate datumAktualizace) {
    this.datumAktualizace = datumAktualizace;
  }


  public ZivnostZaklad druhZivnosti(String druhZivnosti) {
    
    this.druhZivnosti = druhZivnosti;
    return this;
  }

   /**
   * Druh živnosti - kód (ciselnikKod: DruhZivnosti) 
   * @return druhZivnosti
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Druh živnosti - kód (ciselnikKod: DruhZivnosti) ")
  @JsonProperty(JSON_PROPERTY_DRUH_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDruhZivnosti() {
    return druhZivnosti;
  }


  @JsonProperty(JSON_PROPERTY_DRUH_ZIVNOSTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDruhZivnosti(String druhZivnosti) {
    this.druhZivnosti = druhZivnosti;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZivnostZaklad zivnostZaklad = (ZivnostZaklad) o;
    return Objects.equals(this.datumVzniku, zivnostZaklad.datumVzniku) &&
        Objects.equals(this.datumZaniku, zivnostZaklad.datumZaniku) &&
        Objects.equals(this.platnostDo, zivnostZaklad.platnostDo) &&
        Objects.equals(this.predmetPodnikani, zivnostZaklad.predmetPodnikani) &&
        Objects.equals(this.pozastaveniZivnosti, zivnostZaklad.pozastaveniZivnosti) &&
        Objects.equals(this.podminkyProvozovaniZivnosti, zivnostZaklad.podminkyProvozovaniZivnosti) &&
        Objects.equals(this.preruseniZivnosti, zivnostZaklad.preruseniZivnosti) &&
        Objects.equals(this.zivnostBezOz, zivnostZaklad.zivnostBezOz) &&
        Objects.equals(this.datumAktualizace, zivnostZaklad.datumAktualizace) &&
        Objects.equals(this.druhZivnosti, zivnostZaklad.druhZivnosti);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datumVzniku, datumZaniku, platnostDo, predmetPodnikani, pozastaveniZivnosti, podminkyProvozovaniZivnosti, preruseniZivnosti, zivnostBezOz, datumAktualizace, druhZivnosti);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZivnostZaklad {\n");
    sb.append("    datumVzniku: ").append(toIndentedString(datumVzniku)).append("\n");
    sb.append("    datumZaniku: ").append(toIndentedString(datumZaniku)).append("\n");
    sb.append("    platnostDo: ").append(toIndentedString(platnostDo)).append("\n");
    sb.append("    predmetPodnikani: ").append(toIndentedString(predmetPodnikani)).append("\n");
    sb.append("    pozastaveniZivnosti: ").append(toIndentedString(pozastaveniZivnosti)).append("\n");
    sb.append("    podminkyProvozovaniZivnosti: ").append(toIndentedString(podminkyProvozovaniZivnosti)).append("\n");
    sb.append("    preruseniZivnosti: ").append(toIndentedString(preruseniZivnosti)).append("\n");
    sb.append("    zivnostBezOz: ").append(toIndentedString(zivnostBezOz)).append("\n");
    sb.append("    datumAktualizace: ").append(toIndentedString(datumAktualizace)).append("\n");
    sb.append("    druhZivnosti: ").append(toIndentedString(druhZivnosti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

